### ISSUE TITLE
TypeError: _users.default.findOne

### ISSUE THREAD

**Issue by jsamchineme** [fredie7/sendIT#1]
### Error
`TypeError: _users.default.findOne is not a function<br> &nbsp; &nbsp;at signin (/workspace/sendIT/controllers/auth.js:24:10)`

**Comment by jsamchineme** [comment]
This issue is occuring because `data` as you have it here: https://github.com/fredie7/sendIT/blob/master/controllers/auth.js#L24 is an array which does not have any method named `findOne`. Did must be a mix up. use the available array method `find()`.

**Comment by fredie7** [comment]
Actually, the data is an object because it was pulled from a `.json` file. I have corrected this to now use a `.js` file and export an array.
